# Generated by Django 4.2.27 on 2026-03-21 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_access', models.CharField(default='Full Access', max_length=45)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=150)),
                ('artist_municipality', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='prod_name', max_length=150)),
                ('description', models.TextField(blank=True, db_column='prod_description', null=True)),
                ('price', models.DecimalField(db_column='prod_price', decimal_places=2, max_digits=10)),
                ('user_id', models.IntegerField(default=2)),
                ('image', models.ImageField(blank=True, db_column='prod_image_path', null=True, upload_to='artwork_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_ref', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='products.artist')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_municipality', models.CharField(default='Bicol', max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(default='C', max_length=1)),
                ('user_lname', models.CharField(max_length=100)),
                ('user_fname', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=150)),
                ('user_contact_num', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('user_password_hash', models.CharField(default='managed_by_django', max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=1)),
                ('stock_status', models.CharField(default='In Stock', max_length=50)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'timeline',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_total_quantity', models.IntegerField(default=0)),
                ('order_status', models.CharField(default='Pending', max_length=20)),
                ('order_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='products.customerprofile')),
                ('timeline', models.ForeignKey(db_column='timeline_id', on_delete=django.db.models.deletion.CASCADE, to='products.timeline')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('op_quantity', models.IntegerField(db_column='op_quantity', default=1)),
                ('op_subtotal_amount', models.DecimalField(db_column='op_subtotal_amount', decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='products.order')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='products.artwork')),
            ],
            options={
                'db_table': 'op_cart',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='stock',
            field=models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='products.stock'),
        ),
    ]
