# Generated by Django 4.2.27 on 2026-04-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(db_column='ARTIST_ID', primary_key=True, serialize=False)),
                ('artist_name', models.CharField(db_column='ARTIST_NAME', max_length=255, null=True)),
                ('artist_phone_num', models.CharField(db_column='ARTIST_PHONE_NUM', max_length=20, null=True)),
                ('artist_description', models.TextField(db_column='ARTIST_DESCRIPTION', null=True)),
                ('artist_municipality', models.CharField(db_column='ARTIST_MUNICIPALITY', max_length=100, null=True)),
                ('artist_brgy', models.CharField(db_column='ARTIST_BRGY', max_length=100, null=True)),
                ('artist_zipcode', models.CharField(db_column='ARTIST_ZIPCODE', max_length=10, null=True)),
                ('artist_image', models.CharField(db_column='ARTIST_IMAGE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('prod_id', models.AutoField(db_column='PROD_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='PROD_NAME', max_length=255, null=True)),
                ('description', models.TextField(db_column='PROD_DESCRIPTION', null=True)),
                ('price', models.DecimalField(db_column='PROD_PRICE', decimal_places=2, max_digits=10, null=True)),
                ('stock_qty', models.IntegerField(db_column='PROD_STOCK_QTY', null=True)),
                ('image', models.ImageField(blank=True, db_column='PROD_IMAGE', null=True, upload_to='artwork_pics/')),
                ('artist', models.ForeignKey(db_column='ARTIST_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.artist')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='CART_ID', primary_key=True, serialize=False)),
                ('total_items', models.IntegerField(db_column='TOTAL_ITEMS', default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DATE_CREATED')),
                ('user', models.OneToOneField(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CATEGORY_ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CATEGORY_NAME', max_length=100, null=True)),
                ('category_desc', models.TextField(blank=True, db_column='CATEGORY_DESC', null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='PAYMENT_ID', primary_key=True, serialize=False)),
                ('method', models.CharField(db_column='PAYMENT_METHOD', max_length=50, null=True)),
                ('status', models.CharField(db_column='PAYMENT_STATUS', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='PAYMENT_TIMESTAMP')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(db_column='REVIEW_ID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='REVIEW_RATING', null=True)),
                ('description', models.TextField(db_column='REVIEW_DESCRIPTION', null=True)),
                ('image', models.CharField(db_column='REVIEW_IMAGE', max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DATE_CREATED')),
                ('product', models.ForeignKey(db_column='PRODUCT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.artwork')),
                ('user', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='ORDER_ID', primary_key=True, serialize=False)),
                ('shipment_id', models.IntegerField(db_column='SHIPMENT_ID', null=True, unique=True)),
                ('total_qty', models.IntegerField(db_column='ORDER_TOTAL_QUANTITY', null=True)),
                ('delivery_fee', models.DecimalField(db_column='ORDER_DELIVERY_FEE', decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(db_column='ORDER_TOTAL_AMOUNT', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(db_column='ORDER_STATUS', max_length=50, null=True)),
                ('payment', models.OneToOneField(db_column='PAYMENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.payment')),
                ('user', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(db_column='LIKE_ID', primary_key=True, serialize=False)),
                ('date_liked', models.DateTimeField(auto_now_add=True, db_column='DATE_LIKED')),
                ('product', models.ForeignKey(db_column='PRODUCT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.artwork')),
                ('user', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(db_column='ADDRESS_ID', primary_key=True, serialize=False)),
                ('address_type', models.CharField(db_column='ADDRESS_TYPE', max_length=50, null=True)),
                ('phone_num', models.CharField(db_column='ADDRESS_PHONE_NUM', max_length=20, null=True)),
                ('house_num', models.CharField(db_column='ADDRESS_HOUSE_NUM', max_length=20, null=True)),
                ('street', models.CharField(db_column='ADDRESS_STREET', max_length=100, null=True)),
                ('municipality', models.CharField(db_column='ADDRESS_MUNICIPALITY', max_length=100, null=True)),
                ('brgy', models.CharField(db_column='ADDRESS_BRGY', max_length=100, null=True)),
                ('zipcode', models.CharField(db_column='CUST_ZIPCODE', max_length=10, null=True)),
                ('user', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(db_column='QUANTITY', null=True)),
                ('subtotal', models.DecimalField(db_column='SUBTOTAL', decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(db_column='ORDER_ID', on_delete=django.db.models.deletion.CASCADE, to='products.order')),
                ('product', models.ForeignKey(db_column='PROD_ID', on_delete=django.db.models.deletion.CASCADE, to='products.artwork')),
            ],
            options={
                'db_table': 'order_details',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='QUANTITY', default=1)),
                ('is_selected', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(db_column='CART_ID', on_delete=django.db.models.deletion.CASCADE, to='products.cart')),
                ('product', models.ForeignKey(db_column='PRODUCT_ID', on_delete=django.db.models.deletion.CASCADE, to='products.artwork')),
            ],
            options={
                'db_table': 'cart_items',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
