# Generated by Django 4.2.27 on 2026-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_address_profile_pix_artist_user_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_fname',
            field=models.CharField(db_column='ADDRESS_FNAME', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_lname',
            field=models.CharField(db_column='ADDRESS_LNAME', max_length=100, null=True),
        ),
    ]
