# Generated by Django 4.2.27 on 2026-04-22 00:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_fix_artwork_image_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, db_column='PROD_IMAGE', null=True, upload_to=products.models.artwork_image_upload_to),
        ),
    ]
