# Generated by Django 4.2.27 on 2026-04-24 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_reorganize_artwork_images_by_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('application_id', models.AutoField(db_column='APPLICATION_ID', primary_key=True, serialize=False)),
                ('artist_name', models.CharField(db_column='ARTIST_NAME', max_length=255)),
                ('application_status', models.CharField(db_column='APPLICATION_STATUS', default='Pending', max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, db_column='DATE_SUBMITTED')),
                ('date_reviewed', models.DateTimeField(blank=True, db_column='DATE_REVIEWED', null=True)),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artist_application',
            },
        ),
        migrations.CreateModel(
            name='SupplyInventory',
            fields=[
                ('supply_id', models.AutoField(db_column='SUPPLY_ID', primary_key=True, serialize=False)),
                ('supplied_date', models.DateTimeField(auto_now_add=True, db_column='SUPPLIED_DATE')),
                ('supplied_qty', models.IntegerField(db_column='SUPPLIED_QTY')),
                ('product', models.ForeignKey(db_column='PROD_ID', on_delete=django.db.models.deletion.CASCADE, to='products.artwork')),
            ],
            options={
                'db_table': 'supply_inventory',
            },
        ),
        migrations.CreateModel(
            name='ArtistApplicationProduct',
            fields=[
                ('application_product_id', models.AutoField(db_column='APPLICATION_PRODUCT_ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='PROD_NAME', max_length=255)),
                ('product_description', models.TextField(blank=True, db_column='PROD_DESCRIPTION', null=True)),
                ('product_price', models.DecimalField(db_column='PROD_PRICE', decimal_places=2, max_digits=10)),
                ('product_stock_qty', models.IntegerField(db_column='PROD_STOCK_QTY', default=0)),
                ('product_image', models.CharField(blank=True, db_column='PROD_IMAGE', max_length=255, null=True)),
                ('application', models.ForeignKey(db_column='APPLICATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.artistapplication')),
                ('category', models.ForeignKey(db_column='CATEGORY_ID', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'artist_application_products',
            },
        ),
    ]
