# Generated by Django 4.2.27 on 2026-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_popularad'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='artist_image',
            field=models.CharField(blank=True, db_column='ARTIST_IMAGE', max_length=255, null=True),
        ),
    ]
